engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    checks:
      Identical code:
        enabled: false
      Similar code:
        enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
      checks:
        Complexity:
          enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
