language: python
env:
  - CODECLIMATE_REPO_TOKEN=f6808f9c04115688af0d713bc818815baa08e9f290308d20c663eebe0f2a583c
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - pip freeze
  - nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
  - export PYTHONPATH=.:$PYTHONPATH
  - python examples/activerecord.py
  - python examples/all_features.py
  - python examples/eagerload.py
  - python examples/repr.py
  - python examples/smartquery.py
after_success:
  - codeclimate-test-reporter