language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=sqlalchemy_mixins
after_sucess:
  - export CODECLIMATE_REPO_TOKEN=f6808f9c04115688af0d713bc818815baa08e9f290308d20c663eebe0f2a583c && codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=f6808f9c04115688af0d713bc818815baa08e9f290308d20c663eebe0f2a583c codeclimate-test-reporter